name = "apache-2.0"
description = "Quelques informations Ã  propos de la license Apache, version 2.0."

[[embeds]]
title = "Licence Apache, version 2.0 (Apache-2.0)"
thumbnail = "https://opensource.org/files/OSI_Approved_License.png"
description = """
La licence Apache est une license dite permissive dont les conditions principales permettent
la distribution de travaux de toute taille, tout en prÃ©servant la sÃ©curitÃ© lÃ©gale pour les mainteneurs et les
utilisateurs.
Cete licence est l'une des plus utilisÃ©es dans le monde de l'open-source, comptant des projets
comme [Kubernetes](https://github.com/kubernetes/kubernetes/blob/master/LICENSE), [Bazel](https://github.com/bazelbuild/bazel/blob/master/LICENSE)
ou [Swift](https://github.com/apple/swift/blob/main/LICENSE.txt).

    â–¶ï¸ï¸ Open Source Initiative, <https://opensource.org/licenses/Apache-2.0>.
    â–¶ Site officiel, <https://www.apache.org/licenses/LICENSE-2.0>.
    â–¶ï¸ Choose A License, <https://choosealicense.com/licenses/apache-2.0/>.

La fondation Apache recommande fortement l'ajout d'un en-tÃªte dans chaque fichier source pour
Ã©viter les erreurs d'utilisations de la licence par des personnes extÃ©rieures.

Google recommande fortement l'utilisation de `Apache-2.0`. [*(source)*](https://github.com/google/new-project/blob/master/README.md)
"""

[[embeds.fields]]
name = "Permissions"
inline = true
value = """
ğŸ‘Œ Utilisation commerciale
ğŸ‘Œ Distribution
ğŸ‘Œ Modification
ğŸ‘Œ PropriÃ©tÃ© intellectuelle
ğŸ‘Œ Utilisation et modification privÃ©e
"""

[[embeds.fields]]
name = "Conditions"
inline = true
value = """
â• Une copie de la licence doit Ãªtre distribuÃ©e avec le logiciel
â•ï¸ Les modifications apportÃ©es doivent Ãªtre documentÃ©es
"""

[[embeds.fields]]
name = "Limitations"
inline = true
value = """
âŒ ResponsabilitÃ©
âŒ Utilisation de la marque
âŒ Garantie
"""