name = "bsd-3-clause"
description = "Quelques informations Ã  propos de la license BSD Ã  3 clauses."

[[embeds]]
title = "Licence BSD Ã  3 clauses (BSD-3-Clause)"
thumbnail = "https://opensource.org/files/OSI_Approved_License.png"
description = """
Aussi connu sous les noms *"Nouvelle Licence BSD"* ou *"Licence BSD ModifiÃ©e"*, la license BSD
Ã  3 clauses est une Ã©volution de la cÃ©lÃ¨bre licence BSD enlevant la clause publicitaire.
Cette license est populaire dans la communautÃ© open-source et utilisÃ©e par des projets comme
[Flutter](https://github.com/flutter/flutter/blob/master/LICENSE), [LevelDB](https://github.com/google/leveldb/blob/master/LICENSE)
ou [Quill](https://github.com/quilljs/quill/blob/develop/LICENSE).

    â–¶ï¸ï¸ Open Source Initiative, <https://opensource.org/licenses/BSD-3-Clause>.
    â–¶ï¸ Choose A License, <https://choosealicense.com/licenses/bsd-3-clause/>.
"""

[[embeds.fields]]
name = "Permissions"
inline = true
value = """
ğŸ‘Œ Utilisation commerciale
ğŸ‘Œ Distribution
ğŸ‘Œ Modification
ğŸ‘Œ Utilisation et modification privÃ©e
"""

[[embeds.fields]]
name = "Conditions"
inline = true
value = """
â• Une copie de la licence doit Ãªtre distribuÃ©e avec le logiciel
"""

[[embeds.fields]]
name = "Limitations"
inline = true
value = """
âŒ ResponsabilitÃ©
âŒ Garantie
"""