name = "gpl-3"
description = "Quelques informations Ã  propos de la license Publique GÃ©nÃ©rale GNU, version 3."

[[embeds]]
title = "Licence Publique GÃ©nÃ©rale GNU, version 3 (GPL-3.0-only)"
thumbnail = "https://opensource.org/files/OSI_Approved_License.png"
description = """
Connue pour sa rigueur et ses critÃ¨res de qualitÃ©, la licence GPLv3 est l'un des piliers du mouvement [GNU](https://www.gnu.org/)
et du monde du [Logiciel Libre](https://fr.wikipedia.org/wiki/Logiciel_libre).
GPLv3 est la licence de choix pour de nombreux projets *"Libre"* (dans le sens libre), dont [Bash](https://git.savannah.gnu.org/cgit/bash.git/tree/COPYING)
et [GIMP](https://gitlab.gnome.org/GNOME/gimp/-/blob/master/COPYING).

    â–¶ï¸ï¸ Open Source Initiative, <https://opensource.org/licenses/GPL-3.0>.
    â–¶ Site officiel, <https://www.gnu.org/licenses/gpl-3.0.html>.
    â–¶ï¸ Choose A License, <https://choosealicense.com/licenses/gpl-3.0/>.
"""

[[embeds.fields]]
name = "Permissions"
inline = true
value = """
ğŸ‘Œ Utilisation commerciale
ğŸ‘Œ Distribution
ğŸ‘Œ Modification
ğŸ‘Œ PropriÃ©tÃ© intellectuelle
ğŸ‘Œ Utilisation et modification privÃ©e
"""

[[embeds.fields]]
name = "Conditions"
inline = true
value = """
â• Une copie du code source doit Ãªtre distribuÃ©e avec le logiciel (compilÃ©, etc...)
â• Une copie de la licence doit Ãªtre distribuÃ©e avec le logiciel
â• Toutes modifications apportÃ©es doivent Ãªtre publiÃ©e sous la mÃªme licence
â•ï¸ Les modifications apportÃ©es doivent Ãªtre documentÃ©es
"""

[[embeds.fields]]
name = "Limitations"
inline = true
value = """
âŒ ResponsabilitÃ©
âŒ Garantie
"""