name = "mit-license"
description = "Quelques informations Ã  propos de la license MIT."

[[embeds]]
title = "Licence MIT (MIT)"
thumbnail = "https://opensource.org/files/OSI_Approved_License.png"
description = """
Simple, courte mais trÃ¨s efficace, la licence MIT est probablement la licence la plus utilisÃ©e.
Cette derniÃ¨re permet de protÃ©ger l'ensemble d'un projet de maniÃ¨re comprÃ©hensible pour tous.
Parmi les projets sous MIT, nous pouvons retrouver [.NET](https://github.com/dotnet/runtime/blob/main/LICENSE.TXT),
[Ruby on Rails](https://github.com/rails/rails/blob/master/MIT-LICENSE) ou [React](https://github.com/facebook/react).

    â–¶ï¸ï¸ Open Source Initiative, <https://opensource.org/licenses/MIT>.
    â–¶ï¸ Choose A License, <https://choosealicense.com/licenses/mit/>.

La licence MIT est la licence la plus utilisÃ©e pour des modules [NPM](https://npmjs.com).
"""

[[embeds.fields]]
name = "Permissions"
inline = true
value = """
ğŸ‘Œ Utilisation commerciale
ğŸ‘Œ Distribution
ğŸ‘Œ Modification
ğŸ‘Œ Utilisation et modification privÃ©e
"""

[[embeds.fields]]
name = "Conditions"
inline = true
value = """
â• Une copie de la licence doit Ãªtre distribuÃ©e avec le logiciel
"""

[[embeds.fields]]
name = "Limitations"
inline = true
value = """
âŒ ResponsabilitÃ©
âŒ Garantie
"""