name = "opensource"
description = "Une description de l'innitiative Open Source."

[[embeds]]
title = "Initiative Open Source"
description = """
L'[Open Source Initiative (OSI)](https://opensource.org/about) est un organisme ayant pour objectif
de dÃ©finir et de consolider les fondations de la philosophie Open Source
en informatique.

Ã‰tant donnÃ© la rapide croissance de la popularitÃ© du mouvement, il est nÃ©cessaire de savoir dÃ©finir l'open-source.

> L'intÃ©gralitÃ© de la dÃ©finition dans son format original est disponible [ici](https://opensource.org/osd).

Quelques licences considÃ©rÃ©es "open-source" :
> L'intÃ©gralitÃ© des licences triÃ©es alphabÃ©tiquement peut Ãªtre trouvÃ©e [ici](https://opensource.org/licenses/alphabetical).

ğŸ‘‰ [Apache License Version 2.0](https://opensource.org/licenses/Apache-2.0) *(`/tag apache-2.0`)*
ğŸ‘‰ [BSD 3-Clause "New" license](https://opensource.org/licenses/BSD-3-Clause) *(`/tag bsd-3-clause`)*
ğŸ‘‰ [BSD 2-Clause "Simplified" license](https://opensource.org/licenses/BSD-2-Clause)
ğŸ‘‰ [GNU General Public License (GPL)](https://opensource.org/licenses/gpl-license) *(`/tag gpl-3`)*
ğŸ‘‰ [GNU Library General Public License (LGPL)](https://opensource.org/licenses/lgpl-license)
ğŸ‘‰ [MIT license](https://opensource.org/licenses/MIT) *(`/tag mit-license`)*
ğŸ‘‰ [Mozilla Public License 2.0 (MPL)](https://opensource.org/licenses/MPL-2.0)
"""
thumbnail = "https://opensource.org/files/osi_symbol_0.png"

[[embeds.fields]]
name = "Redistribution"
value = """
Une licence ne doit pas restreindre toute entitÃ© de vendre ou de distribuer le logiciel en tant que composant d'un
logiciel plus grand (en tant que dÃ©pendance). Elle ne doit pas imposer de redevances.
"""
inline = true

[[embeds.fields]]
name = "Code Source"
value = """
Le programme doit inclure son code source et autorisÃ© la distribution de ce dernier sous forme compilÃ© ou non.
Il est aussi interdit de proposer du code servant de reprÃ©sentation intermÃ©diaire.
"""
inline = true

[[embeds.fields]]
name = "Modifications et Redistributions"
value = """
Une licence doit autoriser les modifications ou les travaux dÃ©rivÃ©s et permettre la redistribution des modifications
sous les mÃªmes termes que le logiciel original.
"""
inline = true

[[embeds.fields]]
name = "IntÃ©gritÃ© du Travail de l'Auteur"
value = """
Une license peut restreindre la distribution de code source modifiÃ© si cette derniÃ¨re autorise la distribution de
*"patch files"* permettant de modifier le logiciel lors de sa compilation.
Sinon, la licence doit autoriser la distribution de modification tout en demandant d'utiliser un nom diffÃ©rent.
"""
inline = true

[[embeds.fields]]
name = "Discriminations"
value = """
Une licence ne doit pas discriminer un individu ou un groupe d'individu, ni restreindre une entitÃ© d'utiliser le
logiciel dans un but spÃ©cifique (utilisation commerciale, pour la recherche, ...).
Une licence ne doit pas imposer l'utilisation de technologies particuliÃ¨res.
"""
inline = true

[[embeds.fields]]
name = "Partage et Application de la Licence"
value = """
Les droits spÃ©cifiÃ©s par la licence doivent s'appliquer aux entitÃ©s redistribuant ou
utilisant le logiciel.
"""
inline = true

[[embeds.fields]]
name = "Restrictions"
value = """
Les droits exigÃ©s par une licence ne doivent pas Ãªtre exclusifs au logiciel sous certaines conditions,
les droits doivent Ãªtre les mÃªmes, peu importe l'utilisation.
Une licence ne doit pas placer de restrictions sur les logiciels qui dÃ©pendent de la source (une licence ne doit donc
pas obliger les logiciels dÃ©pendants d'Ãªtre open-source eux aussi).
"""
inline = true
